### ISSUE TITLE
The spectral response function is different for sentinel-2A and -2B

### ISSUE THREAD

**Issue by lauraset** [sig-gis/Ecuador_SEPAL#2]
Hello, in the sentinel2.py script, I note that you used predefinedwavelengths of sentinel-2A, but the wavelength is different for sentinel-2A and -2B satellites.  I guess this parameter should change according to relevant satellite.

**Comment by jdilger** [comment]
Hi laurset, nice find there. I added in some logic to check the satellite and switch the predefined wave lengths accordingly.

**Comment by lauraset** [comment]
Hello, jdilger, thank you for your reply. Actually, according to the py6s documentation ( https://py6s.readthedocs.io/), the predefinedwavelengths for band 8A-13 are:
    bandSelect = {
          ...
        'B8A':PredefinedWavelengths.S2A_MSI_8A,
        'B9':PredefinedWavelengths.S2A_MSI_09,
        'B10':PredefinedWavelengths.S2A_MSI_10,
        'B11':PredefinedWavelengths.S2A_MSI_11,
        'B12':PredefinedWavelengths.S2A_MSI_12,
        }
Besides, the SRTM 30  (=ee.Image('USGS/SRTMGL1_003')) may be an alternative.

**Comment by jdilger** [comment]
Hi Laurset, I went and updated the bands to the correct key/values. I am leaving the dem though as there may have been a reason we were using that over the 30m product.
